name: app
description: The main app of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  deps:
    path: ../deps
  flutter:
    sdk: flutter

dev_dependencies:
  pyramid_lint: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - ../design/assets/images/