name: design
description: The design system of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  deps:
    path: ../deps
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  pyramid_lint: ^1.3.0
  slang_build_runner: ^3.29.0
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/_core/constants/
  line_length: 120
  integrations:
    flutter_svg: true
