name: design
description: The design system of flutter advanced boilerplate.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  deps:
    path: ../deps
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  json_serializable: ^6.7.1
  pyramid_lint: ^1.2.0
  slang_build_runner: ^3.28.0
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
    - family: VisueltPro
      fonts:
        - asset: assets/fonts/VisueltPro/VisueltPro-Black.ttf
          weight: 900
        - asset: assets/fonts/VisueltPro/VisueltPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/VisueltPro/VisueltPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/VisueltPro/VisueltPro-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/VisueltPro/VisueltPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/VisueltPro/VisueltPro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/VisueltPro/VisueltPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/VisueltPro/VisueltPro-Light.ttf
          weight: 300
        - asset: assets/fonts/VisueltPro/VisueltPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/VisueltPro/VisueltPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/VisueltPro/VisueltPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/VisueltPro/VisueltPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/VisueltPro/VisueltPro-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/VisueltPro/VisueltPro-Italic.ttf
          style: italic

flutter_gen:
  output: lib/_core/constants/
  line_length: 120
  integrations:
    flutter_svg: true
